# Generated by Django 5.0.6 on 2024-07-13 23:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_organization_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
